import Head from 'next/head'
import { Countdown } from '../components/Countdown/Countdown'
import { Jumbotron } from '../components/Jumbotron/Jumbotron'

export default function Home() {
  return (
    <>
    <div>
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <Jumbotron>
            <Countdown />
          </Jumbotron>
      </main>
    </>
  )
}
